export const metadata = {
    title: 'space',
    description: 'Generated by Next.js',
  }
  
  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
          <div>
              <h4>aaa @@@@@@ layout</h4>
              {children}
          </div>
    )
  }