import Layout from "@/components/Layout"
import { Suspense } from "react"
import Loading from "./loading"
export const metadata = {
  title: 'space',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="zh-CN">
      <body style={{padding:0,margin:0}}>
        <div>
          <Suspense fallback={<Loading />}>
            <Layout>
              {children}
            </Layout>
          </Suspense>
        </div>
      </body>
    </html>
  )
}