import Layout from "@/components/Layout"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div style={{width: '600px', height: '600px', background: 'red'}}>
          <Layout>
            {children}
          </Layout>
        </div>
      </body>
    </html>
  )
}