import Layout from "@/components/Layout"

export const metadata = {
  title: 'space',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="zh-CN">
      <body style={{padding:0,margin:0}}>
        <div>
          <Layout>
            {children}
          </Layout>
        </div>
      </body>
    </html>
  )
}